<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<br>Verification failure: expected [abc] but found [xyz]<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_27_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_27_AEDT_2019.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_32_AEDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_32_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_32_AEDT_2019.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_34_AEDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_34_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_34_AEDT_2019.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Tests" duration-ms="6604" started-at="2019-02-14T08:25:27Z" finished-at="2019-02-14T08:25:34Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="4830" started-at="2019-02-14T08:25:27Z" finished-at="2019-02-14T08:25:32Z">
      <class name="com.XXX.TestCases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.XXX.TestCases.BankManagerLoginTest@4961f6af]" name="loginAsBankManager" duration-ms="4042" started-at="2019-02-14T19:25:27Z" finished-at="2019-02-14T19:25:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successful
	at org.testng.Assert.fail(Assert.java:94)
	at com.XXX.TestCases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br>Verification failure: expected [abc] but found [xyz]<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_27_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_27_AEDT_2019.jpg height=200 width=200></img></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_32_AEDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_32_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_32_AEDT_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.XXX.TestCases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="1726" started-at="2019-02-14T08:25:32Z" finished-at="2019-02-14T08:25:34Z">
      <class name="com.XXX.TestCases.AddCustomerTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.XXX.TestCases.AddCustomerTest@6aaceffd]" name="setup" is-config="true" duration-ms="8188" started-at="2019-02-14T19:25:19Z" finished-at="2019-02-14T19:25:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.XXX.TestCases.AddCustomerTest@6aaceffd]" name="addCustomerTest" duration-ms="1197" started-at="2019-02-14T19:25:32Z" data-provider="dp" finished-at="2019-02-14T19:25:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5768]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully with customer id]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
	at org.testng.Assert.fail(Assert.java:94)
	at com.XXX.TestCases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_34_AEDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Feb_14_19_25_34_AEDT_2019.jpg><img src=Thu_Feb_14_19_25_34_AEDT_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.XXX.TestCases.AddCustomerTest@6aaceffd]" name="tearDown" is-config="true" duration-ms="687" started-at="2019-02-14T19:25:34Z" finished-at="2019-02-14T19:25:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.XXX.TestCases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Tests -->
</testng-results>
